name: Upload Release Package

on:
    release:
        types: [published]

permissions:
    contents: write
    packages: write

jobs:
    tag:
        name: Upload New Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.32.0@v2
              with:
                  php-version: 7.4
                  coverage: none
                  extensions: mbstring, intl
                  tools: composer:v2

            - name: Install Composer dependencies
              uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v3.1.0@v3
              with:
                  composer-options: '--no-progress'

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22

            - name: Install Node.js dependencies
              run: npm ci
              env:
                  CI: true

            - name: Build assets
              run: npm run build:dist

            - name: Create Artifact
              run: |
                  npm run plugin-zip

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: snapwp-helper
                  path: snapwp-helper.zip

            - name: Upload release asset
              uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
              with:
                  files: snapwp-helper.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
