name: Upload Release Package

on:
    release:
        types: [published]

permissions:
    contents: write
    packages: write

jobs:
    tag:
        name: Upload New Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401  # 2.32.0@v2
              with:
                  php-version: 7.4
                  coverage: none
                  extensions: mbstring, intl
                  tools: composer:v2

            - name: Install Composer dependencies
              uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565  # v3.1.0@v3
              with:
                  composer-options: '--no-progress'

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Node.js dependencies
              run: npm ci
              env:
                  CI: true

            - name: Build assets
              run: npm run build:dist

            - name: Create Artifact
              run: |
                  npm run plugin-zip

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: snapwp-helper
                  path: snapwp-helper.zip

            - name: Upload release asset
              uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda  # v2.2.1
              with:
                  files: snapwp-helper.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
